# Kafka datacenters
clusters=clusterA,clusterB

# Define the bootstrap servers for the two Kafka clusters, comma separated brokers
clusterA.bootstrap.servers=brokerA:29091
clusterB.bootstrap.servers=brokerB:29092

# ClusterA and ClusterB configurations
# Replication factor should not be greater than available brokers
clusterA.config.storage.replication.factor=1
clusterB.config.storage.replication.factor=1
clusterA.offset.storage.replication.factor=1
clusterB.offset.storage.replication.factor=1
clusterA.status.storage.replication.factor=1
clusterB.status.storage.replication.factor=1

clusterA->clusterB.enabled=true
clusterB->clusterA.enabled=false

# MirrorMaker configuration
offset-syncs.topic.replication.factor=1
heartbeats.topic.replication.factor=1
checkpoints.topic.replication.factor=1
topics=.*
groups=.*
tasks.max=2
replication.factor=1
refresh.topics.enabled=true
sync.topic.configs.enabled=true
refresh.topics.interval.seconds=30
topics.blacklist=.*[\-\.]internal,.*\.replica,__consumer_offsets
groups.blacklist=console-consumer-.*,connect-.*,__.*
clusterA->clusterB.emit.heartbeats.enabled=true
clusterA->clusterB.emit.checkpoints.enabled=true

replication.policy.class=org.apache.kafka.connect.mirror.IdentityReplicationPolicy


abort.on.send.failure=true


clusterA->clusterB.transforms=srcmeta
clusterA->clusterB.transforms.srcmeta.type=io.spoud.connect.SourceMetaToHeaders
clusterA->clusterB.transforms.srcmeta.partition.fields=cluster,topic,partition
clusterA->clusterB.transforms.srcmeta.offset.fields=offset
clusterA->clusterB.transforms.srcmeta.partition.prefix=source.
clusterA->clusterB.transforms.srcmeta.offset.prefix=source.
